language: java
jdk: oraclejdk8

install: true
script: ./mvnw clean install

branches:
  only:
    - develop

cache:
  directories:
    - $HOME/.m2

before_script:
  - wget https://github.com/IMSGlobal/caliper-common-fixtures/archive/develop.zip
  - unzip develop.zip -d ..
  - mkdir -p src/test/resources/fixtures
  - mv ../caliper-common-fixtures-develop/v1p1 src/test/resources/fixtures
